quarkus.datasource.jdbc-url=jdbc:h2:mem:default
quarkus.datasource.db-kind=h2
quarkus.datasource.h2.console.enabled=true
quarkus.datasource.h2.console.path=/h2-console
quarkus.hibernate-orm.database.generation=drop-and-create

%dev.quarkus.datasource.dev-ui.allow-sql=true
